language: ruby

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip
  - evm list

env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-26.3-travis-linux-xenial
  - EVM_EMACS=emacs-27.1-travis-linux-xenial
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial

script:
  make test
